server:
  port: 8085

spring:
  output:
    ansi:
      enabled: detect
  http:
    converters:
      preferred-json-mapper: jackson
  jackson:
    default-property-inclusion: non_null
    time-zone: UTC
  jpa:
    open-in-view: false
  security:
    user:
      name: dev
      password: dev

management:
  endpoints:
    web:
      exposure:
        include: "health"
  server:
    add-application-context-header: false

app:
  service-info:
    id: "org.ga4gh.service-registry"
    name: "GA4GH Service Registry Reference Implementation"
    type: "org.ga4gh.service-registry:1.0.0"
    description: "Reference implementation of GA4GH Service Registry"
    organization:
      name: "GA4GH"
      url: "https://example.com"
    contact-url: "mailto:support@example.com"
    documentation-url: "https://github.com/ga4gh-discovery/ga4gh-service-registry"
    environment: "dev"
    version: 1.0.0
  service-registry:
    spec-url: https://raw.githubusercontent.com/ga4gh-discovery/ga4gh-service-registry/develop/service-registry.yaml